# Generated by Django 2.2.2 on 2019-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190629_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='short_name',
            field=models.CharField(default=1, max_length=250, verbose_name='Короткое название'),
            preserve_default=False,
        ),
    ]
