# Generated by Django 2.2.2 on 2019-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_social_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
