# Generated by Django 2.2.2 on 2019-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titletag',
            options={'verbose_name': 'SEO title', 'verbose_name_plural': 'SEO titles'},
        ),
        migrations.AlterField(
            model_name='titletag',
            name='url',
            field=models.CharField(max_length=250, verbose_name='URL'),
        ),
    ]
