# Generated by Django 2.2.2 on 2019-06-30 06:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190629_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Cоглашение на обработку персональных данных',
                'verbose_name_plural': 'Cоглашение на обработку персональных данных',
            },
        ),
    ]
