# Generated by Django 2.2.2 on 2019-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_extendedflatpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedflatpage',
            options={'verbose_name': 'Простая страница', 'verbose_name_plural': 'Простые страницы'},
        ),
        migrations.RemoveField(
            model_name='extendedflatpage',
            name='my_order',
        ),
        migrations.AlterField(
            model_name='extendedflatpage',
            name='desc',
            field=models.CharField(default='123123', max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendedflatpage',
            name='keywords',
            field=models.CharField(default='1231 123', max_length=250, verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendedflatpage',
            name='seo_title',
            field=models.CharField(default=' 1323123123', max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
