# Generated by Django 2.2.2 on 2019-06-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20190630_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedFlatPage',
        ),
    ]
