# Generated by Django 2.2.2 on 2019-06-30 13:53

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to=gallery.models.Album.get_picture_url, verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='ImageInAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.ImageInAlbum.get_picture_url, verbose_name='Изображение')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
