# Generated by Django 2.2.2 on 2019-06-30 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='album',
            name='text',
            field=models.TextField(default='12312313', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
