# Generated by Django 2.2.2 on 2019-07-10 19:26

from django.db import migrations, models
import django.db.models.deletion
import services.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('schedule', models.CharField(max_length=250, verbose_name='График')),
                ('one_lesson_price', models.PositiveIntegerField(verbose_name='Цена одного занятия')),
                ('some_lesson_nmb', models.PositiveIntegerField(verbose_name='Количество занятий')),
                ('some_lesson_price', models.PositiveIntegerField(verbose_name='Цена нескольких занятий')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('schedule', models.CharField(max_length=250, verbose_name='График')),
                ('one_lesson_price', models.PositiveIntegerField(verbose_name='Цена одного занятия')),
                ('some_lesson_nmb', models.PositiveIntegerField(verbose_name='Количество занятий')),
                ('some_lesson_price', models.PositiveIntegerField(verbose_name='Цена нескольких занятий')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('categories', models.ManyToManyField(related_name='services', to='services.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('about', models.TextField(verbose_name='О специалисте')),
                ('image', models.ImageField(upload_to=services.models.Specialist.get_picture_url, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('short_name', models.CharField(max_length=250, verbose_name='Короткое название')),
                ('slug_name', models.CharField(max_length=250, verbose_name='Slug название')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='WeekDayServiceElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250, verbose_name='Время')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.Service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.Specialist', verbose_name='Специалист')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.WeekDay', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Услуга в расписании',
                'verbose_name_plural': 'Услуги в расписании',
            },
        ),
        migrations.CreateModel(
            name='WeekDayArtclassElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250, verbose_name='Время')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.Artclass', verbose_name='Кружок')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.Specialist', verbose_name='Специалист')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.WeekDay', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Кружок в расписании',
                'verbose_name_plural': 'Кружки в расписании',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='specialists',
            field=models.ManyToManyField(related_name='services', to='services.Specialist', verbose_name='Специалисты'),
        ),
        migrations.CreateModel(
            name='ImageInService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.ImageInService.get_picture_url, verbose_name='Изображение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ImageInArtclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.ImageInArtclass.get_picture_url, verbose_name='Изображение')),
                ('artclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Artclass', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='artclass',
            name='categories',
            field=models.ManyToManyField(related_name='artclasses', to='services.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='specialists',
            field=models.ManyToManyField(related_name='artclasses', to='services.Specialist', verbose_name='Специалисты'),
        ),
    ]
