# Generated by Django 2.2.2 on 2019-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='services.ServiceCategory', verbose_name='Категории'),
        ),
    ]
