# Generated by Django 2.2.2 on 2019-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_prefix',
            field=models.CharField(default='info', max_length=250, verbose_name='Префикс цвета'),
            preserve_default=False,
        ),
    ]
