# Generated by Django 2.2.2 on 2019-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_color_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title1',
            field=models.CharField(default=123, max_length=120, verbose_name='Название (первая строка)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название (вторая строка)'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title1', 'title2')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
