# Generated by Django 2.2.2 on 2019-07-09 17:23

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190709_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('about', models.TextField(verbose_name='О специалисте')),
                ('image', models.ImageField(upload_to=services.models.Specialist.get_picture_url, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.AddField(
            model_name='artclass',
            name='specialists',
            field=models.ManyToManyField(related_name='artclasses', to='services.Specialist', verbose_name='Специалисты'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialists',
            field=models.ManyToManyField(related_name='services', to='services.Specialist', verbose_name='Специалисты'),
        ),
    ]
