# Generated by Django 2.2.2 on 2019-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190711_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='artclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
