# Generated by Django 2.2.2 on 2019-07-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDayElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250, verbose_name='Время')),
                ('artclass', models.ForeignKey(blank=True, help_text='Выбрать услугу или кружок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekday_elems', to='services.Artclass', verbose_name='Кружок')),
                ('service', models.ForeignKey(blank=True, help_text='Выбрать услугу или кружок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekday_elems', to='services.Service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_elems', to='services.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Пункт в расписании',
                'verbose_name_plural': 'Пункты в расписании',
            },
        ),
    ]
