# Generated by Django 2.2.2 on 2019-07-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_weekdayelem_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDayArtclassElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250, verbose_name='Время')),
                ('artclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.Artclass', verbose_name='Кружок')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.Specialist', verbose_name='Специалист')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artclass_elems', to='services.WeekDay', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Кружок в расписании',
                'verbose_name_plural': 'Кружки в расписании',
            },
        ),
        migrations.CreateModel(
            name='WeekDayServiceElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250, verbose_name='Время')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.Service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.Specialist', verbose_name='Специалист')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_elems', to='services.WeekDay', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Услуга в расписании',
                'verbose_name_plural': 'Услуги в расписании',
            },
        ),
        migrations.DeleteModel(
            name='WeekDayElem',
        ),
    ]
