# Generated by Django 2.2.2 on 2019-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=250, verbose_name='Имя родителя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('child_name', models.CharField(max_length=250, verbose_name='Имя ребенка')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], max_length=20, verbose_name='Пол ребенка')),
                ('text', models.TextField(verbose_name='Ожидания от занятий')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
